version: '3'
services:
  postgres:
    image: "postgres:15.2"
    ports:
    - 5432:5432
    environment:
       POSTGRES_DB: platform
       DB_USER: postgres
       DB_PASSWORD: password
       POSTGRES_PASSWORD: password